[package]
name = "overlinejunior/hearty"
version = "0.3.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
licence = "MIT"
author = "Over"
exclude = ["selene.toml", "roblox.toml"]

[dependencies]
Signal = "sleitnick/signal@^1"
